[theme]

# Primary accent for interactive elements
primaryColor = '#a8dadc'

# Background color for the main content area
backgroundColor = '#1d3557'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#457b9d'

# Color used for almost all text
textColor = '#f1faee'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"